resource "snowflake_database" "new_database" {
  name    = "Ramesh_DB"
  comment = "New database added via Terraform"
}

resource "snowflake_schema" "new_schema" {
  database = snowflake_database.Ramesh_DB.Indp  # or specify an existing database name
   name     = "Indp"
  comment  = "New schema added via Terraform"
}

resource "snowflake_role" "new_role" {
  name    = "Mahesh01"
  comment = "New role added via Terraform"
}

resource "snowflake_database_grant" "new_database_grant" {
  database_name = snowflake_database.new_database.Ramesh_DB
  privilege     = "OWNERSHIP"
  roles         = [snowflake_role.new_role.name]
}

resource "snowflake_schema_grant" "new_schema_grant" {
  database_name = snowflake_database.new_database.Ramesh_DB
  schema_name   = snowflake_schema.new_schema.Indp
  privilege     = "OWNERSHIP"
  roles         = [snowflake_role.new_role.Mahesh01]
}





